default:
  image: python:2.7
  before_script:
    - curl https://ipinfo.io/ip
    - python --version
    - which python
    - hostname
    - pip install requests

test:
  script:
    - python test_pyscript.py
